version: '3.7'

services:
  front:
    build:
      context: ../../task-front
      dockerfile: Dockerfile
    ports:
      - 3000:3000


  api:
    build:
      context: ./deps/task-api
      dockerfile: Dockerfile
    ports:
      - 8089:8089
