version: '3.7'

services:
  front:
    build:
      context: ../../task-front
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  api:
    extends:
      file: "../task-api/docker-compose.e2e.yaml"
      service: api

  db:
    extends:
      file: "../task-api/docker-compose.e2e.yaml"
      service: db
