version: '3.7'

volumes:
  task-db-data:

services:
  api:
    build:
      context: ../../task-api
      dockerfile: Dockerfile
    ports:
      - 8089:8089
    environment:
        TASK_DB_DSN: "host=db port=5432 user=task_user password=task_pw dbname=task_db sslmode=disable"

  db:
    extends:
      file: docker-compose.deps.yaml
      service: db
