version: '3.7'

volumes:
  task-db-data:

services:
  db:
    build: 
      context: ./deps/task-db/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - task-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
